name: Drop Party
main: dropparty\DropParty
version: 1.0.0
description: "Automatic Drop party for PMMP"
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 4.0.0]
author: Netstarv2 